[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SHTC3 Library
    witnessmenow/UniversalTelegramBot
    me-no-dev/AsyncTCP
    mathieucarbou/ESP Async WebServer
    marcoschwartz/LiquidCrystal_I2C
    adafruit/Adafruit Unified Sensor
