[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SHTC3
    witnessmenow/UniversalTelegramBot
    me-no-dev/AsyncTCP
    me-no-dev/ESP Async WebServer
    ayushsharma82/ElegantOTA
    marcoschwartz/LiquidCrystal_I2C
    adafruit/Adafruit Unified Sensor
